/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 WIP.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function WIP({ setHovered }) { // Include setHovered in the props
  const { nodes, materials } = useGLTF('/WIP.glb');
  return (
    <group
      dispose={null}
      position={[0.12, 0.0, 0]} // Centered position
      scale={0.4} // Scale the entire group
      onPointerOver={() => setHovered(true)} // Add onPointerOver handler
      onPointerOut={() => setHovered(false)} // Add onPointerOut handler
      onTouchStart={() => setHovered(true)} // Add onTouchStart handler
      onTouchEnd={() => setHovered(false)} // Add onTouchEnd handler
    >
      <mesh geometry={nodes.Text.geometry} material={materials['Material.001']} rotation={[0.938, 0.518, -0.205]}  />
    </group>
  );
}

useGLTF.preload('/WIP.glb');

export default WIP
